apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "progressive.fullname" . }}
  labels:
{{ include "progressive.labels" . | indent 3 }}
  namespace: {{ .Values.namespace }}
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: {{ .Values.remoteChart.name | default "prometheus" }}
    repoURL: {{ .Values.remoteChart.repo | default "https://kubernetes-charts.storage.googleapis.com" }}
    targetRevision: {{ .Values.remoteChart.revision | default "11.12.0" }}
    {{- if .Values.chartValues }}
    helm:
      values: |
{{ .Values.chartValues | indent 7 }}
    {{- end }}
{{- if .Values.autosync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
